
#config_uttool.yaml
out_path: /Users/Leonardo/Google Drive/investimento/curso_mira/video_aulas
video_list:
   - https://www.youtube.com/watch?v=jLc1i9LB6ws
  # - https://www.youtube.com/watch?v=RZuEG-TtmGA
  # - https://www.youtube.com/watch?v=DggquAatQNA
  # - https://www.youtube.com/watch?v=HFXMxZLW4qA
